### PR TITLE
Add (limited) 'stats' support to Go client

### PR DESCRIPTION
**Pull request by bitfield**
Add support for retrieving outage and downtime stats for checks:

```go
func (s *CheckService) Stats(ctx context.Context, pk int, start, end time.Time) (*CheckStats, *http.Response, error) {
```

### CODE REVIEW

**Comment by mylh** [comment]
I suggest creating a CheckStatsOptions type and move start and end time there for consistency and for future full support of Stats endpoint. Everything else looks good

**Comment by bitfield** [comment]
Thanks @mylh! Updated as suggested.

**Comment by mylh** [comment]
Hi @bitfield I'm sorry I was not fully clear in my last comment about the purpose of CheckStatsOptions type. The idea was to encapsulate _optional_ API endpoint params while keeping required params like check id as corresponding function parameter. I would suggest moving pk back to function params. What do you think?

**Comment by bitfield** [comment]
Yes, that makes sense @mylh. I was looking at `Create()` for a suitable parallel:

```go
func (s *CheckService) Create(ctx context.Context, check *Check) (*Check, *http.Response, error) {
```

Compare with:

```go
func (s *CheckService) Stats(ctx context.Context, opt *CheckStatsOptions) (*CheckStatsResponse, *http.Response, error) {
```

I can see the argument for making the _required_ parameters function parameters, while adding the _optional_ parameters in a struct, and applying this idea to both Stats and Create (and Update).

However, to avoid cramming too many unrelated things into a single PR, I suggest I make a separate PR for that refactoring, and keep this one as it is. How does that sound?

**Comment by mylh** [comment]
I don't think that we should go that far. It is ok to pass all required data to create a check in Check struct since it represents check object with all its fields optional or not. While CheckStatsOptions controls optional parameters of a function execution. And since the change is really small I prefer to keep it all in one PR

**Comment by bitfield** [comment]
I think it's actually a bit more difficult than that to make the case that we should do the same thing two different ways in three different places. I feel like I would find that confusing, as a library user: "Is this the one where I pass all the values in a struct, or is this the one where some things are function parameters and other things go in the struct?"

As I say, I think it's quite reasonable either the _current_ way (everything in a struct), or the _suggested_ way (required values as parameters, optional values as struct). If either principle is applied consistently across the API, it makes sense. What's more difficult to justify is mixing the two principles. Personally, I would vote for the status quo (everything in a struct); I find it a bit neater, and if we were to change the names and types of some of these attributes then it wouldn't change the function signatures.

**Comment by mylh** [comment]
I don't really see two different ways in three different places. We have API methods that 
1) Create, modify objects
2) Fetch list of objects
3) produce additional data
1st type of functions receive and return structs that represents objects
2nd type of functions have required parameters as function objects and optional parameters in struct. Thus library user will not forget to pass required parameter and can totally ignore optional parameter by passing uninitialized struct literal
3 - same logic as 2nd case

I think we need a 3rd opinion here @bazzisoft you thoughts are welcome here

**Comment by bazzisoft** [comment]
@mylh @bitfield I looked at the existing API functions and most consistent to the existing code seems to be the following:

POST/PUT/PATCH - provide single object which includes pk for PUT/PATCH
GET (list) - All params are always optional, provide via object.
GET (single) - pk as function parameter, any other optional params via object.
DELETE - pk as function parameter

**Comment by bitfield** [comment]
Thanks @bazzisoft and @mylh! Updated as suggested.

**Comment by bitfield** [comment]
Once this is merged, shall we tag it `v1.1.0`?

**Pull request merged**
